//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drzi
    {
        public int TrenerIdBedz { get; set; }
        public int CasTreningaIdCasTreninga { get; set; }
    
        public virtual Trener Trener { get; set; }
        public virtual CasTreninga CasTreninga { get; set; }
    }
}
