//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Context : DbContext
    {
        public Model1Context()
            : base("name=Model1Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasTreninga> CasTreningas { get; set; }
        public virtual DbSet<Clan> Clans { get; set; }
        public virtual DbSet<OpremaUteretani> OpremaUteretanis { get; set; }
        public virtual DbSet<Teratana> Teratanas { get; set; }
        public virtual DbSet<Zaposleni> Zaposlenis { get; set; }
        public virtual DbSet<ObicanVezbac> ObicanVezbacs { get; set; }
        public virtual DbSet<Uzima> Uzimas { get; set; }
        public virtual DbSet<Ide> Ides { get; set; }
        public virtual DbSet<ProbniTrening> ProbniTrenings { get; set; }
        public virtual DbSet<Radi> Radis { get; set; }
        public virtual DbSet<Cisti> Cistis { get; set; }
        public virtual DbSet<Drzi> Drzis { get; set; }
    }
}
